POST http://localhost:8080/kingdom/buildings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NDU3NDM2MDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJmdXJrZXN6In0.EbEppw_CfPvVhT7hz0Rs6GeQ33FmA_uyc13lE9BQbprhgkyA8qrVejSNfUptj3mC2a5oaeXrZXbDZ4oFAfemcg

{
  "type": "academy"
}

### Get buildings

GET http://localhost:8080/kingdom/buildings
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2MTc0MDA4MDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJrZWxlbWVuIn0.ioc5uEEWWbTizqkjNoNrR1kbZtRCIpUq7uX1PsuDu20fLQp9rDEvlOqXrJih8ENwSObUr7cbxBvtIRTDcTY4WQ
Accept: application/json

### Get building

GET http://localhost:8080/kingdom/buildings/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2MTc0MDA4MDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJmdXJrZXN6In0.82V0FgQJnDcTiW6LS6TewF4KttCVUTSxcQlhWqNZkWrLI_IUgW0d8e9ZYde8fM6Gl6W3nKN_rFhc_6sRS0kmmg
Accept: application/json

### PUT buildings

PUT http://localhost:8080/kingdom/buildings/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2MTc0MDA4MDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJrZWxlbWVuIn0.ioc5uEEWWbTizqkjNoNrR1kbZtRCIpUq7uX1PsuDu20fLQp9rDEvlOqXrJih8ENwSObUr7cbxBvtIRTDcTY4WQ

{
  "level": 2
}


