version: '3'

services:
  springboot-docker-compose-app-container:
    image: tribe_backend/v1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8080:8080"
    environment:
      - DB_URL
      - JWT_SECRET
      - PWD
      - HIB_DIA
      - EMAIL_USER
      - EMAIL_PWD