version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  myapp-spring:
    image: tribe_backend/v1
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_NAME=MyAppDb
      - DATABASE_PORT=3306
      - DB_URL=jdbc:mysql://myapp-mysql:3306/MyAppDb?useSSL=false&allowPublicKeyRetrieval=true
      - USERNAME=myapp-user
      - JWT_SECRET=12345
      - PWD=password
      - HIB_DIA=org.hibernate.dialect.MySQL5Dialect
      - EMAIL_USER=e26c1b338d5cff
      - EMAIL_PWD=abdb0349edb97d