package com.greenfoxacademy.springwebapp.resource.services;

import com.greenfoxacademy.springwebapp.building.models.BuildingEntity;
import com.greenfoxacademy.springwebapp.building.models.enums.BuildingType;
import com.greenfoxacademy.springwebapp.common.services.TimeService;
import com.greenfoxacademy.springwebapp.kingdom.models.KingdomEntity;
import com.greenfoxacademy.springwebapp.resource.models.ResourceEntity;
import com.greenfoxacademy.springwebapp.resource.models.dtos.ResourceListResponseDTO;
import com.greenfoxacademy.springwebapp.resource.models.dtos.ResourceResponseDTO;
import com.greenfoxacademy.springwebapp.resource.models.enums.ResourceType;
import com.greenfoxacademy.springwebapp.resource.repositories.ResourceRepository;
import lombok.AllArgsConstructor;
import org.springframework.core.env.Environment;
import org.springframework.stereotype.Service;

import java.util.stream.Collectors;
@AllArgsConstructor
@Service
public class ResourceServiceImpl implements ResourceService {
  private ResourceRepository resourceRepository;
  private TimeService timeService;
  private Environment env;


  public boolean hasResourcesForTroop() {
    // TODO: has Resources For Troops creation
    return true;
  }

  @Override
  public boolean hasResourcesForBuilding() {
    // TODO: hasResourcesForBuilding
    return false;
  }

  @Override
  public ResourceEntity saveResource(ResourceEntity resourceEntity) {
    return resourceRepository.save(resourceEntity);
  }

  @Override
  public ResourceListResponseDTO convertKingdomResourcesToListResponseDTO(KingdomEntity kingdom) {
    return ResourceListResponseDTO.builder()
        .withResources(kingdom.getResources().stream()
            .map(ResourceResponseDTO::new)
            .collect(Collectors.toList()))
        .build();
  }

  @Override
  public void updateResourceGeneration(KingdomEntity kingdom, BuildingEntity building) {
    //1.finding particular kingdom´s resource to be later updated
    ResourceEntity resource = findResourceBasedOnBuildingType(kingdom,building.getType());

    //2.calculating resources which were generated by kindom until new building is done/upgraded
    Integer generatedResourcesInMeantime = calculateResourcesUntilBuildingIsFinished(building, resource);

    //3.calculating new resource generation value
    Integer newResourceGeneration = recalculateResourceGeneration(resource, building);

    //4.updating selected resource entity properties in Database
    //....nutno zjistit jak spustit funkci se spožděním
    resource.setGeneration(newResourceGeneration);
    resource.setAmount(resource.getAmount()+generatedResourcesInMeantime);
    resource.setUpdatedAt(building.getFinishedAt());
    resourceRepository.save(resource);

  }

  public ResourceEntity findResourceBasedOnBuildingType(KingdomEntity kingdom, Enum buildingType) {
    ResourceEntity resource;
    if(buildingType == BuildingType.FARM) {
      resource = kingdom.getResources().stream()
          .filter(a -> a.getType() == ResourceType.FOOD)
          .findFirst()
          .orElse(null);
    } else if (buildingType == BuildingType.MINE) {
      resource = kingdom.getResources().stream()
          .filter(a -> a.getType() == ResourceType.GOLD)
          .findFirst()
          .orElse(null);
    } else return null;

    return resource;
  }

  public Integer calculateResourcesUntilBuildingIsFinished(BuildingEntity building, ResourceEntity resource) {
    Long lastUpdateTime = resource.getUpdatedAt();
    Long finishedTime = building.getFinishedAt();
    int timeInSeconds = timeService.getTimeBetween(finishedTime, lastUpdateTime);
    //in this variant resource was created only when full minute passed (fractions of minute are excluded)
    int timeInFullMinutes = timeInSeconds%60;

    return timeInFullMinutes*resource.getGeneration();
  }

  public Integer recalculateResourceGeneration(ResourceEntity resource, BuildingEntity building) {
    //distingushing food/gold in case the values differ in future
    Integer defaultFood = Integer.parseInt(env.getProperty("resourceEntity.food"));
    Integer defaultGold = Integer.parseInt(env.getProperty("resourceEntity.gold"));

    if (resource.getType() == ResourceType.FOOD) {
      return resource.getGeneration() + building.getLevel()*defaultFood + defaultFood;
    }

    if (resource.getType() == ResourceType.GOLD) {
      return resource.getGeneration() + building.getLevel()*defaultGold + defaultGold;
    }

    return null;
  }
}
