POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "PetrWillSleep",
  "password": "password222"
}
###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password"
}
###