POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "kelemen",
  "password": "password",
  "email": "kelemen9417@gmail.com"
}

###

POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "",
  "password": ""
}

###

POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "petrN",
  "password": "password",
  "email": "ppetrnovotny@gmail.com"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "furkesz",
  "password": "password"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "petrN",
  "password": "password"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "kelemen",
  "password": "password"
}