GET http://localhost:8080/kingdom/resources
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2MTM3NzU2MDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJmdXJrZXN6In0.DtUdBear4jyYArWfPOCmvbxwFqY0lXPkxyGP8Kqs_2KrVLs_q1oF7Q6VWiaUgWyTNqyIKSjGEQyLcrXDB7X5_w
Accept: application/json

###
