### Get kingdom
### kingdom/resources
GET http://localhost:8080/kingdom/resources
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NjE4MTA0MDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJwZXRyTiJ9.b-L-Eyz-5mfocm2bgfgBKkoFnsQAtwCbX9TXapO6NAA9E5xS_--DAOAtJ7k-cnVKJGgnK_ty9TzedXc_C31Qdw
Accept: application/json


### Get kingdom
### kingdom/{id}
GET http://localhost:8080/kingdom/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NDgxNjI4MDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJwZXRyTiJ9.hxMbO7Lv0YKeAW_vTzoE6z6Hz5G-O6sRqIL0LKg3vDPRGxmpqTtVMoxhR6B_FIhW6gIbPM9KlD3gzofUNVRE5Q
Accept: application/json

### PUT kingdom
### kingdom
PUT http://localhost:8080/kingdom
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NDY4NjY4MDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJmdXJrZXN6In0.TrrhSXz6j-SS0t3vzZqZS002XnUexSaXJlwTeIZOYdRc0mRQaDW_YX5_94HWuydREAorVbo2QMzOMzdERlJx_Q
Content-Type: application/json

{
  "name": "test"
}

### PUT kingdom
### kingdom
PUT http://localhost:8080/kingdom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NDg3NjQwMDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJmdXJrZXN6In0.u29oapzaTwbZjD9Yj4WFSQnuv9InV2vFZx5f6G4bn5wHY2W1lmQO1KLMpbP8gHqwSVvA8IfWpWhr3ld1nPTFMQ

{
  "name": "Furkesz's Kingdom"
}