### Get kingdom troops

GET http://localhost:8080/kingdom/troops
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2Mjg5Nzg0MDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJmdXJrZXN6In0.7RN7TcP7eWhXKwvU1VbQ9LXjq0o9MjuT_FKSSQlEqqr3LrPW5xR80EWCDCbEq7NSkpzXxk4yAT7TnMp79MyHYw
Accept: application/json

### POST kingdom createTroop

POST http://localhost:8080/kingdom/troops
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NjE4MTA0MDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJwZXRyTiJ9.b-L-Eyz-5mfocm2bgfgBKkoFnsQAtwCbX9TXapO6NAA9E5xS_--DAOAtJ7k-cnVKJGgnK_ty9TzedXc_C31Qdw

{
  "buildingId": 3
}

### Zdenek:
### Get kingdom troop - Ok troop

GET http://localhost:8080/kingdom/troops/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NDQ5NjYwMDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJ6ZGVuZWsifQ.3T3ob1vgDZH2ohKTCJk_qPaURKTxcOFtv2mQTwR5vmala80t9pcgj_ITtD6bQxRrzIBbLFbH56nOTe11KwvZoA
Accept: application/json

### Get kingdom troop - forbiddenException

GET http://localhost:8080/kingdom/troops/6
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NDQ5NjYwMDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJ6ZGVuZWsifQ.3T3ob1vgDZH2ohKTCJk_qPaURKTxcOFtv2mQTwR5vmala80t9pcgj_ITtD6bQxRrzIBbLFbH56nOTe11KwvZoA
Accept: application/json

### Get kingdom troop - IdNotFoundException

GET http://localhost:8080/kingdom/troops/100
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NDQ5NjYwMDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJ6ZGVuZWsifQ.3T3ob1vgDZH2ohKTCJk_qPaURKTxcOFtv2mQTwR5vmala80t9pcgj_ITtD6bQxRrzIBbLFbH56nOTe11KwvZoA
Accept: application/json