### Get buildings

GET http://localhost:8080/erase/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NDg1OTEyMDAsImtpbmdkb21JZCI6MSwidXNlcm5hbWUiOiJmdXJrZXN6In0.bAc4vnE7X29qRlgCFzczm6_HZs4VwIRMfNFwwfHhMkfTPeeNyfZFafKDpna4R2lYV96HtklH_tS9Xf78f6CkKw
Accept: application/json


###

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "petrN",
  "password": "password",
  "email": "ppetrnovotny@gmail.com"
}

###